name: Deploy to Render

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render Webhook
      run: curl -X POST 'https://api.render.com/deploy/srv-cje0u7ivvtos73bf24tg?key=IuyACWJxW2o'
